Repository nutgram/nutgram, pull requests merged in 2023-09, with the labels that each got.

#557 Replace ip safe mode
  src/RunningMode/Webhook.php
  tests/E2E/RunningModeTest.php
  tests/Feature/WebhookSafeModeTest.php
Labels: enhancement

#560 Add PHP 8.3 to the GitHub Actions workflow
  .github/workflows/php.yml
Labels: enhancement

#565 Fix regression for sendMediaGroup
  src/Telegram/Endpoints/AvailableMethods.php
  tests/Feature/EndpointsTest.php
Labels: bug

#561 Fix BUTTON_DATA_INVALID using inline menu
  src/Conversations/InlineMenu.php
  src/Telegram/Limits.php
Labels: bug

#562 Add ValidatesWebData trait
  phpunit.xml.dist
  src/Exception/InvalidDataException.php
  src/Nutgram.php
  src/Support/ValidatesWebData.php
  src/Telegram/Web/Entity.php
  src/Telegram/Web/LoginData.php
  src/Telegram/Web/WebAppChat.php
  src/Telegram/Web/WebAppData.php
  src/Telegram/Web/WebAppUser.php
  src/Testing/FakeNutgram.php
  tests/Feature/Web/ValidateLoginDataTest.php
  tests/Feature/Web/ValidateWebAppTest.php
Labels: enhancement

#553 Fix chunked endpoints
  src/Nutgram.php
  src/Support/Helpers.php
  src/Telegram/Client.php
  src/Telegram/ProvidesHttpResponse.php
  tests/Feature/BotTest.php
  tests/Unit/WordWrapTest.php
Labels: bug, help wanted

#569 Add the ability to start conversations for specific user/chat
  src/Conversations/Conversation.php
  tests/Feature/ConversationTest.php
Labels: enhancement

#573 Fix missing static make method and add support for ParseMode enum
  src/Telegram/Types/Inline/InlineQueryResultArticle.php
  src/Telegram/Types/Input/InputTextMessageContent.php
Labels: bug

#575 Add onChosenInlineResultQuery handler
  src/Handlers/Listeners/UpdateListeners.php
  src/Handlers/ResolveHandlers.php
  tests/Feature/Handlers/UpdateHandlersTest.php
Labels: enhancement

#578 Fix missing support for underscores in bot command names when used with bot username set
  src/Telegram/Types/Message/Message.php
  src/Testing/Asserts.php
  tests/Feature/HandlerTest.php
  tests/Feature/Handlers/MessageHandlersTest.php
  tests/Fixtures/Updates/command_tag_valid.json
Labels: bug

#579 Add the ability to disable handler registration
  src/Handlers/Handler.php
  src/Handlers/HandlerGroup.php
  src/Handlers/ResolveHandlers.php
  src/Support/Disable.php
  tests/Feature/DisabledHandlerTest.php
Labels: enhancement, PoC

#580 Update to Bot API 6.9
  README.md
  src/Telegram/Endpoints/AvailableMethods.php
  src/Telegram/Types/Chat/ChatAdministratorRights.php
  src/Telegram/Types/Chat/ChatMemberAdministrator.php
  src/Telegram/Types/Forum/WriteAccessAllowed.php
  src/Telegram/Web/WebAppUser.php
Labels: Bot API Update

#584 Fix regex matching
  src/Handlers/Handler.php
  tests/Feature/PatternsTest.php
Labels: bug
