Repository nutgram/nutgram, pull requests merged in 2024-04, with the labels that each got.

#680 Update to Bot API 7.2 - March 31, 2024
  README.md
  src/Configuration.php
  src/Handlers/Listeners/UpdateListeners.php
  src/Handlers/Type/Command.php
  src/Proxies/UpdateProxy.php
  src/Telegram/Endpoints/AvailableMethods.php
  src/Telegram/Endpoints/CustomEndpoints.php
  src/Telegram/Endpoints/Games.php
  src/Telegram/Endpoints/Payments.php
  src/Telegram/Endpoints/Stickers.php
  src/Telegram/Properties/UpdateType.php
  src/Telegram/Types/Business/BusinessConnection.php
  src/Telegram/Types/Business/BusinessIntro.php
  src/Telegram/Types/Business/BusinessLocation.php
  src/Telegram/Types/Business/BusinessMessagesDeleted.php
  src/Telegram/Types/Business/BusinessOpeningHours.php
  src/Telegram/Types/Business/BusinessOpeningHoursInterval.php
  src/Telegram/Types/Chat/Chat.php
  src/Telegram/Types/Common/Update.php
  src/Telegram/Types/Input/InputInvoiceMessageContent.php
  src/Telegram/Types/Input/InputSticker.php
  src/Telegram/Types/Keyboard/KeyboardButtonRequestChat.php
  src/Telegram/Types/Keyboard/KeyboardButtonRequestUsers.php
  src/Telegram/Types/Message/Message.php
  src/Telegram/Types/Shared/ChatShared.php
  src/Telegram/Types/Shared/SharedUser.php
  src/Telegram/Types/Shared/UsersShared.php
  src/Telegram/Types/Sticker/StickerSet.php
  src/Telegram/Types/User/Birthdate.php
  src/Telegram/Types/User/User.php
  tests/Datasets/business_connection.php
  tests/Datasets/business_message.php
  tests/Datasets/deleted_business_messages.php
  tests/Datasets/edited_business_message.php
  tests/Feature/EndpointsTest.php
  tests/Feature/Listeners/UpdateListenersTest.php
  tests/Fixtures/Updates/business_connection.json
  tests/Fixtures/Updates/business_message.json
  tests/Fixtures/Updates/deleted_business_messages.json
  tests/Fixtures/Updates/edited_business_message.json
  tests/Fixtures/Updates/users_shared.json
Labels: bot api update

#686 Add react method to Message class
  src/Telegram/Types/Message/Message.php
Labels: enhancement

#690 Add DeepLink Support Class
  src/Support/DeepLink.php
  src/Support/Helpers.php
  tests/Unit/DeepLinkTest.php
Labels: enhancement

#691 Optimize archive size + refactor
  .gitattributes
  .gitignore
  README.md
Labels: enhancement

#698 Fix hydration mask position for stickers
  src/Telegram/Types/Sticker/MaskPosition.php
  tests/Fixtures/Updates/sticker.json
Labels: bug
